export default [
    {
        id:1,
        description:"Developed a Tic Tac Toe game using ReactJS to hone my front-end development skills in HTML5, CSS3, and JavaScript.",
        link:"LIVE LINK",
        coverImg: "tictactoe.png",
        codelink:"CODE LINK",
        projecturl:"https://tic-tac-toe-project-vijay.netlify.app/",
        githuburl:"https://github.com/Vijay8130/tictactoe_game",
        projectname:"Tic-Tac-Toe Game"
    },
    {
        id:2,
        description:"Built a single-player Blackjack game using ReactJS, HTML5, CSS3, and JavaScript. Designed a user-friendly interface with Figma and utilized version control with Git and GitHub.",
        link:"LIVE LINK",
        coverImg:"blackjack.png",
        codelink:"CODE LINK",
        projectname:"Blackjack Casino Game",
        projecturl:"https://blackjack-game-project.netlify.app",
        githuburl:"https://github.com/Vijay8130/Blackjack-Game",
    },
    {
        id:3,
        description:"Built a web-based Gym Rep Counter using ReactJS, HTML5, CSS3, and JavaScript. Designed a user-friendly interface with Figma and utilized version control with Git for efficient development.",
        link:"LIVE LINK",
        codelink:"CODE LINK",
        coverImg:"caloriecounter.png",
        projectname:"Gym Rep Counter",
        projecturl:"https://main--gym-rep-counter.netlify.app/",
        githuburl:"https://github.com/Vijay8130/Gym-Rep-Counter",

    },
    {
        id:4,
        description:"Crafted a dynamic Digital Business Card with ReactJS and modern web technologies (HTML5, CSS3) for a seamless and interactive way to share contact information.",
        link:"LIVE LINK",
        codelink:"CODE LINK",
        coverImg:"digitalbusinesscard.png",
        projectname:"Digital Business Card",
        projecturl:"https://vjverma-business-card.netlify.app/",
        githuburl:"https://github.com/Vijay8130/digitalcard",
    },
    {
      id:5,
     description:"Built a Random Quote Machine using ReactJS to display inspirational quotes. Fetched data using an API and employed HTML5, CSS3, and JavaScript to create a visually appealing and interactive user experience. Leveraged Figma for interface design and utilizeGit for version control.",
     link:"LIVE LINK",
     codelink:"CODE LINK",
     coverImg:"randomquote.png",
     projectname:"Random Quote Machine",
     projecturl:"https://freecodecamp-random-quote-machine.netlify.app/",
     githuburl:"https://github.com/Vijay8130/random-quote",
    },
    {
        id:6,
        certificate:1,
        photo:"responsive.png",
        certificateurl:"https://www.freecodecamp.org/certification/VIJAYVERMA/responsive-web-design",
    },
    {   id:7,
        certificate:2,
        photo:"dsa.png",
        certificateurl:"https://www.freecodecamp.org/certification/VIJAYVERMA/javascript-algorithms-and-data-structures",
    },
    {   id:8,
        certificate:3,
        photo:"frontend.png",
        certificateurl:"https://www.freecodecamp.org/certification/VIJAYVERMA/front-end-development-libraries",
    },
    {
        id:9,
        certificate:4,
        photo:"javascript.png",
        certificateurl:"https://scrimba.com/certificate/u4xKQbt9/gjavascript",
    },
   
]


